services:
  screeps:
    image: ghcr.io/jomik/screeps-server:edge
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped
    command: >
      sh -c "
      npm run setup || true &&
      node main.js
      "

  mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: unless-stopped

  client:
    image: "node:20"
    volumes:
      - ${SCREEPS_NW_PATH:?"SCREEPS_NW_PATH not set"}:/screeps.nw
      # Defines a volume for the NPM cache to speed up startup
      # when the container is recreated
      - client-npm-cache:/root/.npm
    command: >
      npx screepers-steamless-client
      --package /screeps.nw
      --host 0.0.0.0
      --internal_backend http://screeps:21025
    ports:
      - "${SCREEPS_PROXY_HOST:-127.0.0.1}:8080:8080/tcp"
    depends_on:
      - screeps
    restart: unless-stopped
volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:
  client-npm-cache:

